import { DataProviderId, DataProviderStatus } from '../types/market';

export const PROVIDER_CATALOG: DataProviderStatus[] = [
  {
    id: 'twelvedata',
    name: 'TwelveData Public API',
    isAvailable: true,
    isActive: true,
    latencyMs: 145,
    lastSuccessTimestamp: Date.now(),
    failureCount: 0,
    statusMessage: 'Streaming 1-Min GBP/USD Public Feed',
    requiresApiKey: false,
  },
  {
    id: 'yahoofinance',
    name: 'Yahoo Finance Public Feed',
    isAvailable: true,
    isActive: false,
    latencyMs: 180,
    lastSuccessTimestamp: Date.now(),
    failureCount: 0,
    statusMessage: 'Ready (Public FX Stream Fallback)',
    requiresApiKey: false,
  },
  {
    id: 'alphavantage',
    name: 'AlphaVantage API',
    isAvailable: true,
    isActive: false,
    latencyMs: 220,
    lastSuccessTimestamp: Date.now(),
    failureCount: 0,
    statusMessage: 'Ready (Requires Free Key for high frequency)',
    requiresApiKey: true,
  },
  {
    id: 'polygon',
    name: 'Polygon.io FX Feed',
    isAvailable: true,
    isActive: false,
    latencyMs: 95,
    lastSuccessTimestamp: Date.now(),
    failureCount: 0,
    statusMessage: 'Ready (WebSocket / REST)',
    requiresApiKey: true,
  },
  {
    id: 'metatrader5',
    name: 'MetaTrader 5 Bridge',
    isAvailable: true,
    isActive: false,
    latencyMs: 40,
    lastSuccessTimestamp: Date.now(),
    failureCount: 0,
    statusMessage: 'Ready (Local IPC Bridge)',
    requiresApiKey: false,
  },
  {
    id: 'oanda',
    name: 'OANDA v20 REST API',
    isAvailable: true,
    isActive: false,
    latencyMs: 110,
    lastSuccessTimestamp: Date.now(),
    failureCount: 0,
    statusMessage: 'Ready (Institutional FX Feed)',
    requiresApiKey: true,
  },
  {
    id: 'interactivebrokers',
    name: 'Interactive Brokers TWS',
    isAvailable: true,
    isActive: false,
    latencyMs: 65,
    lastSuccessTimestamp: Date.now(),
    failureCount: 0,
    statusMessage: 'Ready (TWS Gateway)',
    requiresApiKey: false,
  },
  {
    id: 'tradingview',
    name: 'TradingView Compatible Stream',
    isAvailable: true,
    isActive: false,
    latencyMs: 130,
    lastSuccessTimestamp: Date.now(),
    failureCount: 0,
    statusMessage: 'Ready (UDF Feed)',
    requiresApiKey: false,
  },
  {
    id: 'synthetic',
    name: 'Quant Synthetic FX Engine',
    isAvailable: true,
    isActive: false,
    latencyMs: 12,
    lastSuccessTimestamp: Date.now(),
    failureCount: 0,
    statusMessage: 'Active (Institutional Real-time Simulation)',
    requiresApiKey: false,
  },
];
